name: React App Deployment
on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: afrihealth-website
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
#    - run: git pull origin main
    - run: npm cache clean --force
    
    - run: rm -rf node_modules
    
 #   - name: Install Packages
    -  run: npm install
    
#    - name: Build page
    -  run: npm build
    
    -  run: cd /home/ubuntu/afrihealth-website/_work/afrihealth_desktop/afrihealth_desktop
    
    -  run: pm2 status && pm2 stop afrihealth-website &&  pm2 delete afrihealth-website
    
    -  run: pm2 start yarn --interpreter bash --name afrihealth-website -- start
    
    -  run: pm2 status
