name: React App Deployment
on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: afrihealth-website
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
#    - run: git pull origin main
    
 #   - name: Install Packages
    -  run: npm install
    
#    - name: Build page
    -  run: npm run build
